name = "hrm-trunghai"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "hrm-database"
database_id = "9b49bd33-e3d9-417c-aa2c-f5b422f6a30f"

